using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PassportIdentDict : MonoBehaviour
{
    Dictionary<int, string> passportIdentDict;
    Dictionary<string, int> DictCountryThreeLetterToDigit;
    public string detectedPassportString;
    public string detectedFullCountryName;
    public int detectedPassportNumber;

    public void initDict()
    {
        passportIdentDict = new Dictionary<int, string>
        {
            {0, "Germany"},
            {1, "Andorra"},
            {2, "United Arab Emirates"},
            {3, "Afghanistan"},
            {4, "Antigua & Barbuda"},
            {5, "Albania"},
            {6, "Armenia"},
            {7, "Angola"},
            {8, "Argentina"},
            {9, "Austria"},
            {10, "Australia"},
            {11, "Azerbaijan"},
            {12, "Bosnia & Herzegovina"},
            {13, "Barbados"},
            {14, "Bangladesh"},
            {15, "Belgium"},
            {16, "Burkina Faso"},
            {17, "Bulgaria"},
            {18, "Bahrain"},
            {19, "Burundi"},
            {20, "Benin"},
            {21, "Brunei"},
            {22, "Bolivia"},
            {23, "Brazil"},
            {24, "Bahamas"},
            {25, "Bhutan"},
            {26, "Botswana"},
            {27, "Belarus"},
            {28, "Belize"},
            {29, "Canada"},
            {30, "DR Congo"},
            {31, "Central African Republic"},
            {32, "Congo"},
            {33, "Switzerland"},
            {34, "Coted'Ivoire"},
            {35, "Chile"},
            {36, "Cameroon"},
            {37, "China"},
            {38, "Colombia"},
            {39, "Costa Rica"},
            {40, "Cuba"},
            {41, "Cape Verde"},
            {42, "Cyprus"},
            {43, "Czech Republic"},
            {44, "Germany"},
            {45, "Djibouti"},
            {46, "Denmark"},
            {47, "Dominica"},
            {48, "Dominican Republic"},
            {49, "Algeria"},
            {50, "Ecuador"},
            {51, "Estonia"},
            {52, "Egypt"},
            {53, "Eritrea"},
            {54, "Spain"},
            {55, "Ethiopia"},
            {56, "Finland"},
            {57, "Fiji"},
            {58, "Micronesia"},
            {59, "France"},
            {60, "Gabon"},
            {61, "United Kingdom"},
            {62, "Grenada"},
            {63, "Georgia"},
            {64, "Ghana"},
            {65, "Gambia"},
            {66, "Guinea"},
            {67, "Equatorial Guinea"},
            {68, "Greece"},
            {69, "Guatemala"},
            {70, "Guinea-Bissau"},
            {71, "Guyana"},
            {72, "Hong Kong"},
            {73, "Honduras"},
            {74, "Croatia"},
            {75, "Haiti"},
            {76, "Hungary"},
            {77, "Indonesia"},
            {78, "Ireland"},
            {79, "Israel"},
            {80, "India"},
            {81, "Iraq"},
            {82, "Iran"},
            {83, "Iceland"},
            {84, "Italy"},
            {85, "Jamaica"},
            {86, "Jordan"},
            {87, "Japan"},
            {88, "Kenya"},
            {89, "Kyrgyzstan"},
            {90, "Cambodia"},
            {91, "Kiribati"},
            {92, "Comoros"},
            {93, "St Kitts & Nevis"},
            {94, "North Korea"},
            {95, "South Korea"},
            {96, "Kuwait"},
            {97, "Kazakhstan"},
            {98, "Laos"},
            {99, "Lebanon"},
            {100, "Saint Lucia"},
            {101, "Liechtenstein"},
            {102, "Sri Lanka"},
            {103, "Liberia"},
            {104, "Lesotho"},
            {105, "Lithuania"},
            {106, "Luxembourg"},
            {107, "Latvia"},
            {108, "Libya"},
            {109, "Morocco"},
            {110, "Monaco"},
            {111, "Moldova"},
            {112, "Montenegro"},
            {113, "Madagascar"},
            {114, "Marshall Islands"},
            {115, "North Macedonia"},
            {116, "Mali"},
            {117, "Myanmar"},
            {118, "Mongolia"},
            {119, "Macao"},
            {120, "Mauritania"},
            {121, "Malta"},
            {122, "Mauritius"},
            {123, "Maldives"},
            {124, "Malawi"},
            {125, "Mexico"},
            {126, "Malaysia"},
            {127, "Mozambique"},
            {128, "Namibia"},
            {129, "Niger"},
            {130, "Nigeria"},
            {131, "Nicaragua"},
            {132, "Netherlands"},
            {133, "Norway"},
            {134, "Nepal"},
            {135, "Nauru"},
            {136, "New Zealand"},
            {137, "Oman"},
            {138, "Panama"},
            {139, "Peru"},
            {140, "Papua New Guinea"},
            {141, "Philippines"},
            {142, "Pakistan"},
            {143, "Poland"},
            {144, "Palestine"},
            {145, "Portugal"},
            {146, "Palau"},
            {147, "Paraguay"},
            {148, "Qatar"},
            {149, "Kosovo"},
            {150, "Romania"},
            {151, "Serbia"},
            {152, "Russia"},
            {153, "Rwanda"},
            {154, "Saudi Arabia"},
            {155, "Solomon Islands"},
            {156, "Seychelles"},
            {157, "Sudan"},
            {158, "Sweden"},
            {159, "Singapore"},
            {160, "Slovenia"},
            {161, "Slovakia"},
            {162, "Sierra Leone"},
            {163, "San Marino"},
            {164, "Senegal"},
            {165, "Somalia"},
            {166, "Suriname"},
            {167, "South Sudan"},
            {168, "Sao Tome and Principe"},
            {169, "El Salvador"},
            {170, "Syria"},
            {171, "Eswatini"},
            {172, "Chad"},
            {173, "Togo"},
            {174, "Thailand"},
            {175, "Tajikistan"},
            {176, "Timor-Leste"},
            {177, "Turkmenistan"},
            {178, "Tunisia"},
            {179, "Tonga"},
            {180, "Turkey"},
            {181, "Trinidad and Tobago"},
            {182, "Tuvalu"},
            {183, "Taiwan"},
            {184, "Tanzania"},
            {185, "Ukraine"},
            {186, "Uganda"},
            {187, "United States of America"},
            {188, "Uruguay"},
            {189, "Uzbekistan"},
            {190, "Vatican City State"},
            {191, "St. Vincent & the Grenadines"},
            {192, "Venezuela"},
            {193, "Vietnam"},
            {194, "Vanuatu"},
            {195, "Samoa"},
            {196, "Yemen"},
            {197, "South Africa"},
            {198, "Zambia"},
            {199, "Zimbabwe"},
            {200, "United Kingdom"}
        };
    }

    public void InitDictCountryThreeLetterToDigit() //Is it actually used in the end?
    {
        DictCountryThreeLetterToDigit = new Dictionary<string, int>
        {
            { "AND", 1},
            { "ARE", 2},
            { "AFG", 3},
            { "ATG", 4},
            { "ALB", 5},
            { "ARM", 6},
            { "AGO", 7},
            { "ARG", 8},
            { "AUT", 9},
            { "AUS", 10},
            { "AZE", 11},
            { "BIH", 12},
            { "BRB", 13},
            { "BGD", 14},
            { "BEL", 15},
            { "BFA", 16},
            { "BGR", 17},
            { "BHR", 18},
            { "BDI", 19},
            { "BEN", 20},
            { "BRN", 21},
            { "BOL", 22},
            { "BRA", 23},
            { "BHS", 24},
            { "BTN", 25},
            { "BWA", 26},
            { "BLR", 27},
            { "BLZ", 28},
            { "CAN", 29},
            { "COD", 30},
            { "CAF", 31},
            { "COG", 32},
            { "CHE", 33},
            { "CIV", 34},
            { "CHL", 35},
            { "CMR", 36},
            { "CHN", 37},
            { "COL", 38},
            { "CRI", 39},
            { "CUB", 40},
            { "CPV", 41},
            { "CYP", 42},
            { "CZE", 43},
            { "DEU", 44},
            { "DJI", 45},
            { "DNK", 46},
            { "DMA", 47},
            { "DOM", 48},
            { "DZA", 49},
            { "ECU", 50},
            { "EST", 51},
            { "EGY", 52},
            { "ERI", 53},
            { "ESP", 54},
            { "ETH", 55},
            { "FIN", 56},
            { "FJI", 57},
            { "FSM", 58},
            { "FRA", 59},
            { "GAB", 60},
            { "GBR", 61},
            { "GRD", 62},
            { "GEO", 63},
            { "GHA", 64},
            { "GMB", 65},
            { "GIN", 66},
            { "GNQ", 67},
            { "GRC", 68},
            { "GTM", 69},
            { "GNB", 70},
            { "GUY", 71},
            { "HKG", 72},
            { "HND", 73},
            { "HRV", 74},
            { "HTI", 75},
            { "HUN", 76},
            { "IDN", 77},
            { "IRL", 78},
            { "ISR", 79},
            { "IND", 80},
            { "IRQ", 81},
            { "IRN", 82},
            { "ISL", 83},
            { "ITA", 84},
            { "JAM", 85},
            { "JOR", 86},
            { "JPN", 87},
            { "KEN", 88},
            { "KGZ", 89},
            { "KHM", 90},
            { "KIR", 91},
            { "COM", 92},
            { "KNA", 93},
            { "PRK", 94},
            { "KOR", 95},
            { "KWT", 96},
            { "KAZ", 97},
            { "LAO", 98},
            { "LBN", 99},
            { "LCA", 100},
            { "LIE", 101},
            { "LKA", 102},
            { "LBR", 103},
            { "LSO", 104},
            { "LTU", 105},
            { "LUX", 106},
            { "LVA", 107},
            { "LBY", 108},
            { "MAR", 109},
            { "MCO", 110},
            { "MDA", 111},
            { "MNE", 112},
            { "MDG", 113},
            { "MHL", 114},
            { "MKD", 115},
            { "MLI", 116},
            { "MMR", 117},
            { "MNG", 118},
            { "MAC", 119},
            { "MRT", 120},
            { "MLT", 121},
            { "MUS", 122},
            { "MDV", 123},
            { "MWI", 124},
            { "MEX", 125},
            { "MYS", 126},
            { "MOZ", 127},
            { "NAM", 128},
            { "NER", 129},
            { "NGA", 130},
            { "NIC", 131},
            { "NLD", 132},
            { "NOR", 133},
            { "NPL", 134},
            { "NRU", 135},
            { "NZL", 136},
            { "OMN", 137},
            { "PAN", 138},
            { "PER", 139},
            { "PNG", 140},
            { "PHL", 141},
            { "PAK", 142},
            { "POL", 143},
            { "PSE", 144},
            { "PRT", 145},
            { "PLW", 146},
            { "PRY", 147},
            { "QAT", 148},
            { "KOS", 149},
            { "ROU", 150},
            { "SRB", 151},
            { "RUS", 152},
            { "RWA", 153},
            { "SAU", 154},
            { "SLB", 155},
            { "SYC", 156},
            { "SDN", 157},
            { "SWE", 158},
            { "SGP", 159},
            { "SVN", 160},
            { "SVK", 161},
            { "SLE", 162},
            { "SMR", 163},
            { "SEN", 164},
            { "SOM", 165},
            { "SUR", 166},
            { "SSD", 167},
            { "STP", 168},
            { "SLV", 169},
            { "SYR", 170},
            { "SWZ", 171},
            { "TCD", 172},
            { "TGO", 173},
            { "THA", 174},
            { "TJK", 175},
            { "TLS", 176},
            { "TKM", 177},
            { "TUN", 178},
            { "TON", 179},
            { "TUR", 180},
            { "TTO", 181},
            { "TUV", 182},
            { "TWN", 183},
            { "TZA", 184},
            { "UKR", 185},
            { "UGA", 186},
            { "USA", 187},
            { "URY", 188},
            { "UZB", 189},
            { "VAT", 190},
            { "VCT", 191},
            { "VEN", 192},
            { "VNM", 193},
            { "VUT", 194},
            { "WSM", 195},
            { "YEM", 196},
            { "ZAF", 197},
            { "ZMB", 198},
            { "ZWE", 199},
            { "GBR", 200}
        };
    }

    void Start()
    {
        initDict();
    }

    public string catchPassportIntToString (int receivedPassportInt)
    {
        detectedPassportString = passportIdentDict[receivedPassportInt];
        return detectedPassportString;
    }

    public int catchPassportThreeLetterToThreeNumber (string receivedPassportThreeLetter)
    {
        detectedPassportNumber = DictCountryThreeLetterToDigit[receivedPassportThreeLetter];
        return detectedPassportNumber;
    }

    public string catchDictThreeLetterToFullname (string receivedPassportThreeLetter)
    {
        int temp;
        temp = DictCountryThreeLetterToDigit[receivedPassportThreeLetter];
        detectedFullCountryName = passportIdentDict[temp];
        return detectedFullCountryName;
    }
}
